name: flet_agentview
description: AI Agent chat view using Syncfusion AI AssistView
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flet:
    path: ../../../../../../../packages/flet

  syncfusion_flutter_chat: any
