name: flet_einput
description: Custom Flet input controls (text, slider) with on_key_code scripting
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flet:
    path: ../../../../../../../packages/flet

  flet_micropython:
    path: ../../../../flet-micropython/src/flutter/flet_micropython

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
